<?php
date_default_timezone_set("Asia/Tehran");

$Channel = [
    "Argotaz"
    "AlienVPN402",
"aries_init",
"azadi_az_inja_migzare",
"bright_vpn",
"CloudCityy",
"ConfigsHUB",
"Cov2ray",
"customv2ray",
"daorzadannet",
"DarkVPNpro",
"DirectVPN",
"EXOGAMERS",
"FalconPolV2rayNG",
"free_v2rayy",
"free4allVPN",
"freeconfigv2",
"FreeIranT",
"freeiranweb",
"freev2raygood",
"hashmakvpn",
"hassan_saboorii",
"Helix_Servers",
"INIT1984",
"internet4iran",
"ipV2Ray",
"Iran_Config",
"iran_ray",
"iransubzero",
"iSegaro",
"Jeyksatan",
"kiava",
"lagvpn13",
"LegenderY_Servers",
"LoRd_uL4mo",
"lrnbymaa",
"MehradLearn",
"MsV2ray",
"MTConfig",
"Napsternetvirani",
"NetAccount",
"NIM_VPN_ir",
"oneclickvpnkeys",
"Outline_Vpn",
"OutlineVpnOfficial",
"ovpn2",
"PAINB0Y",
"Pinkpotatocloud",
"PrivateVPNs",
"proxy_kafee",
"Proxy_PJ",
"ProxyFn",
"proxystore11",
"proxyymeliii",
"prrofile_purple",
"Qv2raychannel",
"SafeNet_Server",
"server01012",
"ServerNett",
"ShadowProxy66",
"ShadowSocks_s",
"shopingv2ray",
"talentvpn",
"TheHotVPN",
"UnlimitedDev",
"v2_team",
"v2freevpn",
"v2ray_confings2",
"v2ray_outlineir",
"v2ray_swhil",
"v2ray_vpn_ir",
"v2ray1_ng",
"V2rayng_Fast",
"v2rayNG_Matsuri",
"v2rayNG_VPNN",
"V2rayNGn",
"v2rayNGNeT",
"V2rayngninja",
"v2rayngrit",
"v2rayngvpn",
"V2RayTz",
"v2rayvmess",
"vless_vmess",
"VlessConfig",
"vmess_vless_v2rayng",
"vmessorg",
"VmessProtocol",
"vpn_ioss",
"vpn_proxy_custom",
"vpn_tehran",
"vpn_xw",
"vpnfail_v2ray",
"VpnProSec",
"vpnsal",
"WomanLifeFreedomVPN",
"X_Her0",
"xrayproxy",
"xrayzxn"

];
$Types = [
"AlienVPN402" => ["ss"],
"aries_init" => ["vmess", "vless"],
"azadi_az_inja_migzare" => ["vless", ss],
"bright_vpn" => ["vless", "ss"],
"CloudCityy" => ["vless"],
"ConfigsHUB" => ["vmess", "vless", "trojan"],
"Cov2ray" => ["vmess"],
"customv2ray" => ["vmess", "vless"],
"daorzadannet" => ["vmess", "vless"],
"DarkVPNpro" => ["vless"],
"freeiranweb" => ["vless"],
"DirectVPN" => ["trojan"],
"EXOGAMERS" => ["vless"],
"FalconPolV2rayNG" => ["vless"],
"free_v2rayy" => ["vmess", "vless"],
"free4allVPN" => ["vmess", ss],
"freeconfigv2" => ["vmess", "vless"],
"FreeIranT" => ["vless"],
"freev2raygood" => ["vmess", "vless"],
"hashmakvpn" => ["vmess"],
"hassan_saboorii" => ["vmess", "vless"],
"Helix_Servers" => ["vless"],
"INIT1984" => ["vless"],
"internet4iran" => ["vless"],
"ipV2Ray" => ["vless"],
"Iran_Config" => ["vmess", "vless"],
"iran_ray" => ["vless"],
"iransubzero" => ["vmess", "vless","ss","trojan"],
"iSegaro" => ["vless"],
"Jeyksatan" => ["vmess", "trojan"],
"kiava" => ["vless"],
"lagvpn13" => ["vless"],
"LegenderY_Servers" => ["vless"],
"LoRd_uL4mo" => ["vmess", "vless"],
"Argotaz" => ["vmess", "vless"],
"lrnbymaa" => ["vless"],
"MehradLearn" => ["vless"],
"MsV2ray" => ["vless"],
"MTConfig" => ["vmess", "vless", "ss"],
"Napsternetvirani" => ["vmess"],
"NetAccount" => ["trojan"],
"NIM_VPN_ir" => ["vless"],
"oneclickvpnkeys" => ["vmess", "trojan"],
"Outline_Vpn" => ["vless"],
"OutlineVpnOfficial" => ["ss"],
"ovpn2" => ["vmess", "vless", "trojan"],
"PAINB0Y" => ["vless","vmess","trojan","ss"],
"Pinkpotatocloud" => ["vmess", "vless"],
"PrivateVPNs" => ["trojan"],
"proxy_kafee" => ["vless"],
"Proxy_PJ" => ["vmess", "vless"],
"ProxyFn" => ["vless"],
"proxystore11" => ["vless"],
"proxyymeliii" => ["vmess", "vless", "trojan", "ss"],
"prrofile_purple" => ["vmess", "vless"],
"Qv2raychannel" => ["vless"],
"SafeNet_Server" => ["vmess", "vless"],
"server01012" => ["vmess"],
"ServerNett" => ["vless"],
"ShadowProxy66" => ["vmess", "vless"],
"ShadowSocks_s" => ["vless"],
"shopingv2ray" => ["vless"],
"talentvpn" => ["vless"],
"TheHotVPN" => ["vless"],
"UnlimitedDev" => ["vless"],
"v2_team" => ["vmess", "vless"],
"v2freevpn" => ["vless"],
"v2ray_confings2" => ["vmess", "vless","ss","trojan"],
"v2ray_outlineir" => ["vmess"],
"v2ray_swhil" => ["vmess", "vless", "trojan"],
"v2ray_vpn_ir" => ["vmess", "vless", "trojan"],
"v2ray1_ng" => ["vmess", "vless", "trojan"],
"V2rayng_Fast" => ["vmess"],
"v2rayNG_Matsuri" => ["vless"],
"v2rayNG_VPNN" => ["vless"],
"V2rayNGn" => ["vmess", "vless"],
"v2rayNGNeT" => ["vless"],
"V2rayngninja" => ["vless", "ss"],
"v2rayngrit" => ["vmess", "vless","ss","trojan"],
"v2rayngvpn" => ["vless"],
"V2RayTz" => ["vless", "trojan"],
"v2rayvmess" => ["vmess", "vless"],
"vless_vmess" => ["vmess", "vless"],
"VlessConfig" => ["vless"],
"vmess_vless_v2rayng" => ["vmess", "vless", "trojan", "ss"],
"vmessorg" => ["vmess", "vless"],
"VmessProtocol" => ["vless", "trojan", "ss"],
"vpn_ioss" => ["vmess"],
"vpn_proxy_custom" => ["vless"],
"vpn_tehran" => ["vmess", "vless", "trojan"],
"vpn_xw" => ["vless"],
"vpnfail_v2ray" => ["vmess"],
"VpnProSec" => ["vless"],
"vpnsal" => ["vmess", "vless"],
"WomanLifeFreedomVPN" => ["vless"],
"X_Her0" => ["vless"],
"xrayproxy" => ["vless"],
"xrayzxn" => ["vmess", "vless", "trojan", "ss"],
];

?>
