<?php
date_default_timezone_set("Asia/Tehran");

$Channel = [
    "V2rayNGn",
    "free4allVPN",
    "PrivateVPNs",
    "DirectVPN",
    "ProxyFn",
    "v2ray_outlineir",
    "NetAccount",
    "oneclickvpnkeys",
    "daorzadannet",
    "Outline_Vpn",
    "vpn_xw",
    "prrofile_purple",
    "ShadowSocks_s",
    "azadi_az_inja_migzare",
    "WomanLifeFreedomVPN",
    "internet4iran",
    "LegenderY_Servers",
    "vpnfail_v2ray",
    "UnlimitedDev",
    "vmessorg",
    "v2rayNG_Matsuri",
    "v2rayngvpn",
    "vpn_ioss",
    "v2freevpn",
    "customv2ray",
    "FalconPolV2rayNG",
    "Jeyksatan",
    "hassan_saboorii",
    "v2rayvmess",
    "v2rayNGNeT",
    "server01012",
    "ShadowProxy66",
    "ipV2Ray",
    "kiava",
    "Helix_Servers",
    "PAINB0Y",
    "VpnProSec",
    "VlessConfig",
    "NIM_VPN_ir",
    "hashmakvpn",
    "X_Her0",
    "Napsternetvirani",
    "iran_ray",
    "INIT1984",
    "EXOGAMERS",
    "ServerNett",
    "Pinkpotatocloud",
    "CloudCityy",
    "DarkVPNpro",
    "AlienVPN402",
"aries_init",
"bright_vpn",
"ConfigsHUB",
"Cov2ray",
"customv2ray",
"free_v2rayy",
"freeconfigv2",
"FreeIranT",
"freev2raygood",
"Iran_Config",
"iransubzero",
"iSegaro",
"lagvpn13",
"LegenderY_Servers",
"LoRd_uL4mo",
"lrnbymaa",
"MehradLearn",
"MsV2ray",
"MTConfig",
"OutlineVpnOfficial",
"ovpn2",
"proxy_kafee",
"Proxy_PJ",
"proxystore11",
"proxyymeliii",
"Qv2raychannel",
"SafeNet_Server",
"shopingv2ray",
"talentvpn",
"TheHotVPN",
"UnlimitedDev",
"v2_team",
"v2freevpn",
"v2ray_confings2",
"v2ray_swhil",
"v2ray_vpn_ir",
"v2ray1_ng",
"V2rayng_Fast",
"v2rayNG_Matsuri",
"v2rayNG_VPNN",
"V2rayngninja",
"v2rayngrit",
"v2rayngvpn",
"V2RayTz",
"vless_vmess",
"vmess_vless_v2rayng",
"vmessorg",
"VmessProtocol",
"vpn_ioss",
"vpn_proxy_custom",
"vpn_tehran",
"vpnfail_v2ray",
"vpnsal",
"xrayproxy",
"xrayzxn",
];
$Types = [
    "V2rayNGn" => ["vmess", "vless"],
    "free4allVPN" => ["vmess", "ss"],
    "PrivateVPNs" => ["trojan"],
    "DirectVPN" => ["trojan"],
    "ProxyFn" => ["vless"],
    "v2ray_outlineir" => ["vmess"],
    "NetAccount" => ["trojan"],
    "oneclickvpnkeys" => ["vmess", "trojan"],
    "daorzadannet" => ["vmess", "vless"],
    "Outline_Vpn" => ["vless"],
    "vpn_xw" => ["vless"],
    "prrofile_purple" => ["vmess", "vless"],
    "ShadowSocks_s" => ["vless"],
    "azadi_az_inja_migzare" => ["vless", "ss"],
    "WomanLifeFreedomVPN" => ["vless"],
    "internet4iran" => ["vless"],
    "customv2ray" => ["vmess", "vless"],
    "LegenderY_Servers" => ["vless"],
    "vpnfail_v2ray" => ["vmess"],
    "UnlimitedDev" => ["vless"],
    "vmessorg" => ["vmess", "vless"],
    "v2rayNG_Matsuri" => ["vless"],
    "v2rayngvpn" => ["vless"],
    "vpn_ioss" => ["vmess"],
    "v2freevpn" => ["vless"],
    "customv2ray" => ["vmess", "vless"],
    "FalconPolV2rayNG" => ["vless"],
    "Jeyksatan" => ["vmess", "trojan"],
    "hassan_saboorii" => ["vmess", "vless"],
    "v2rayvmess" => ["vmess", "vless"],
    "v2rayNGNeT" => ["vless"],
    "server01012" => ["vmess"],
    "ShadowProxy66" => ["vmess", "vless"],
    "ipV2Ray" => ["vless"],
    "kiava" => ["vless"],
    "Helix_Servers" => ["vless"],
    "PAINB0Y" => ["vless"],
    "VpnProSec" => ["vless"],
    "VlessConfig" => ["vless"],
    "NIM_VPN_ir" => ["vless"],
    "hashmakvpn" => ["vmess"],
    "X_Her0" => ["vless"],
    "Napsternetvirani" => ["vmess"],
    "iran_ray" => ["vless"],
    "INIT1984" => ["vless"],
    "EXOGAMERS" => ["vless"],
    "ServerNett" => ["vless"],
    "Pinkpotatocloud" => ["vmess", "vless"],
    "CloudCityy" => ["vless"],
    "DarkVPNpro" => ["vless"],
];

?>